### ISSUE TITLE
Debian 8.4 Jessie (multi-screen) xflux blinking

### ISSUE THREAD

**Issue by dragGH102** [xflux-gui/xflux-gui#10]
I love xflux.
On Windows f.lux works excellently but on my machine (Debian 8 64bit, 2 screens: laptop + external) every time I activate xflux My displays (both) keep blinking (like there was some interference) and it's very difficult to use this way.
I am looking forward to hearing from you.

Thank you in advance and keep up the good work!

**Comment by ntc2** [comment]
Not sure how to debug this. E.g. I'm using xflux on multiple monitors in Ubuntu 16.04 (and 15.10 in the past) with no problems.

**Comment by ntc2** [comment]
@dragGH102: could you try running `xflux` manually on the command line, i.e. not via `fluxgui`, and report back?

**Comment by dragGH102** [comment]
@ntc2 Interesting, I reinstalled xflux-gui from scratch and both gui (I run it directly with python) and CLI seems working on both screens.
I'll close the issue for now and reopen it if it occurs again.

**Comment by ntc2** [comment]
Glad to hear you got it working! If you have this issue again, and *it also happens when you run `xflux` directly on the command line*, then I think the bug is in `xflux` itself, and not in `fluxgui`. In that case, please file a bug upstream with the `xflux` maintainers. I can't find a bug tracker at justgetflux.com, but perhaps you would file the bug here: https://forum.justgetflux.com/category/7/linux.
