### ISSUE TITLE
Color options

### ISSUE THREAD

**Issue by skelic2** [xflux-gui/xflux-gui#15]
Hi, I see that xfluxgui use dark-red as the default color. I like green color, and wouldn't it be great if other color options also added into the program? Says, blue, green, and purple?

**Comment by ntc2** [comment]
The `xflux-gui` project is only responsible for the Linux Flux GUI, not the Flux software itself. So, this type of suggestion is out of scope for our project, but you could suggest it to the main Flux developers. However, I don't think it makes sense: the point of flux is to reduce the amount of *blue* light emitted by your monitor, e.g. because the blue light keeps you up at night. So, the red color is probably implied by the goal of removing blue. You can read about it more here: https://justgetflux.com/research.html. I don't actually know anything about the details.

**Comment by skelic2** [comment]
Oh I see. Thanks for the information.
