### ISSUE TITLE
Mint shows two identical packages when opening the PPA

### ISSUE THREAD

**Issue by dandv** [xflux-gui/xflux-gui#24]
![image](https://cloud.githubusercontent.com/assets/33569/17579881/845ceb5c-5f4e-11e6-8cf9-e62ab881162c.png)

**Comment by itsabear** [comment]
does new + updated ppa package still shows this problem?

**Comment by ntc2** [comment]
This is not a bug with xflux-gui itself; we don't maintain the PPA.

**Comment by dandv** [comment]
> This is not a bug with xflux-gui itself; we don't maintain the PPA.

While that is accurate, it still leads to a user experience that can be improved.

Do you know what is the right place to file this bug?

**Comment by ntc2** [comment]
@dandv: the PPA is here: https://launchpad.net/~nathan-renniewaldock/+archive/ubuntu/flux.

You might want to debug this more before filing a bug with the PPA though: in your screenshot, the two packages appear identical. Can you find some representation (e.g. through `apt-cache`) of these packages that shows them as actually different? I don't know much about APT, so I don't know how to debug this myself.

Oh, maybe I've identified the difference. Try these commands:

``` shell
$ apt-cache policy fluxgui
fluxgui:
  Installed: (none)
  Candidate: 1.1.9~20160808-g4125e70-1~xenial
  Version table:
     1.1.9~20160808-g4125e70-1~xenial 500
        500 http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu xenial/main amd64 Packages
        500 http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu xenial/main i386 Packages
```
I see two versions of `fluxgui` there, for two different architectures (i386 and amd64). When I do a `apt-cache policy` search for standard packages, e.g. Firefox, it only lists an amd64 version. I wonder if your GUI package manager (you didn't say which one it was) is listing the two different architectures?

Other commands I try only list `fluxgui` once, presumably because they don't make architecture distinctions:
``` shell
$ aptitude search fluxgui
p   fluxgui                        - f.lux indicator applet is an indicator ap
```

``` shell
$ apt-cache search fluxgui                                               
fluxgui - f.lux indicator applet is an indicator applet to control xflux, an
```
