### ISSUE TITLE
Color change is sudden. No option for changing over a 60minute period

### ISSUE THREAD

**Issue by dumle29** [xflux-gui/xflux-gui#43]
Hey there, I'm used to f.lux on windows, and on there I have an option set, where the color temperature will gradually lower over 60 minutes, instead of doing it suddenly. Is this a limitation of xflux or the gui?

**Comment by ntc2** [comment]
I believe this is a limitation of `xflux` itself, but @herf should know.

**Comment by herf** [comment]
Yes, we have a version (for Android) which shares all the parameters and code with the desktop (e.g., Mac). It would be pretty easy to port it back to xflux, and I'd just have to figure out how to lock the IPC permissions down a little better (probably per-user socket would be ok)?

Our top ten xflux bugs are due to using the console for IPC (which just doesn't work), so using a proper domain socket would fix a lot of bugs.

Essentially the "Mac" code adds: a wake time, and a color temperature for "late night". There are a ton more tunable parameters, but they're not exposed.

**Comment by ntc2** [comment]
Thanks @herf! I close this as "won't fix" for now, and we can revisit when the port happens.
