### ISSUE TITLE
xflux goes defunct when "nighttime color temperature" is set < 2000

### ISSUE THREAD

**Issue by davekaufman** [xflux-gui/xflux-gui#51]
## Steps:

1. run fluxgui
2. open preferences
3. set nighttime temperature to any value lower then 2000 (choosing either "sunset/sunrise" or "match flame")

## Result: 
xflux process goes defunct and screen temperature does not change

## Root Cause: 
Running xflux with temp setting lower than 2000 seems to be unsupported. 
_e.g._ `xflux -l 39.50,-98.35 -k 1850`  fails with error: `Your kelvin color is out of range. We support 2000-10000K.`

**Comment by ntc2** [comment]
Thanks for finding the root cause here! I'm to blame: https://github.com/xflux-gui/xflux-gui/commit/8140fcdb2a697da87535a7e55cef37456d2d83a0 :D

Interestingly, it seems `xflux` (the program that `fluxgui` uses to set the screen temp) does support these low temps in preview mode, so it's probably an arbitrary limitation of `xflux`. You can try previewing a low temp in `xflux` by quitting `fluxgui` and running

    xflux -l 0 -g 0 -nofork

and then entering a low temp, for example

    k=1000<enter>

to set the preview temp to 1000.

In any case, these low temp options will need to be removed from `fluxgui`.

**Comment by cipri-tom** [comment]
shouldn't this be reported to xflux so they add support for those ?

**Comment by ntc2** [comment]
@cipri-tom, note that `xflux` reports that these color temps are not supported; see the "root cause" section in the issue description. So, we could ask for these color temps to be supported, but `xflux` team already knows they are not. The we thing is that it seems like an arbitrary restriction.

Maybe @herf can tell us why?
