### ISSUE TITLE
Release a new version.

### ISSUE THREAD

**Issue by ntc2** [xflux-gui/xflux-gui#53]
The version in the PPA is out of date again: https://launchpad.net/~nathan-renniewaldock/+archive/ubuntu/flux.

- [ ] update the debian/changelog.
- [ ] contact PPA maintainer @NHellFire.

**Comment by ntc2** [comment]
Looking at the package names in the PPA, it looks like they've been recently updated actually! For example I see

    1.1.9~20170116-gaaeae23-1~xenial

which is 2017 January 16th, and `aaeae23` was the most recent commit before today, on also on January 16th: https://github.com/xflux-gui/xflux-gui/commit/aaeae23dc63f7d3ea2de4b7c0c5d166d1aac49ea

Perhaps the PPA gets updated automatically on new commits?

**Comment by NHellFire** [comment]
PPA is automatically built daily from git (currently master as there's no tags).

**Comment by ntc2** [comment]
@NHellFire great! So if I started tagging releases, would it automatically update when there was a new tag? Does the tag need any kind of special format?

**Comment by NHellFire** [comment]
I'd need to change it to build tags, but yep. Tag format doesn't matter
much, v1.1.10 is fine.

On 22 Feb 2017 01:30, "Nathan Collins" <notifications@github.com> wrote:

@NHellFire <https://github.com/NHellFire> great! So if I started tagging
releases, would it automatically update when there was a new tag? Does the
tag need any kind of special format?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/xflux-gui/xflux-gui/issues/53#issuecomment-281538896>,
or mute the thread

**Comment by ntc2** [comment]
If I started tagging releases, would it be easy to have two packages available concurrently:

1. the most recent tagged version;
2. the tip of the `master` branch?

I think the current setup where the PPA automatically updates on each commit to `master` is great, because the PPA is always current, so for now we probably don't need to bother with building tags. Moreover, if we were only building tags, then the PPA would get out of date between tagged releases. That's the motivation for having both packages available, but since `fluxgui` seems pretty stable, it's probably not worth bothering with the two concurrent releases.

**Comment by Kilian** [comment]
We could consider to do development on a develop branch and merge back to master once it's deemed "stable enough", or with pull requests.

With other project, I usually have a grace period between things I commit to master and an official release, which does use the tagging format. 

Both work, but I think having a two-branch strategy is easier?

**Comment by ntc2** [comment]
The tricky part, I think, is making sure the development version actually gets tested before becoming the stable version. Right now, since the PPA is automatically rebuilt on each commit, the development version gets tested, but there is no stable version. Having two packages available would work as long as some people still installed the development version.

So far `fluxgui` is pretty stable, so I don't think there's much need for a separate stable version. But if we ever broke it badly, it would be nice if people could simple go back to the stable version by installing a different package. That seems like the main motivation for having a separate stable release.

**Comment by NHellFire** [comment]
Easy enough to do. I'd either need to make a new PPA for the dev version or
rename the package.

On 25 Feb 2017 02:13, "Nathan Collins" <notifications@github.com> wrote:

If I started tagging releases, would it be easy to have two packages
available concurrently:

   1. the most recent tagged version;
   2. the tip of the master branch?

I think the current setup where the PPA automatically updates on each
commit to master is great, because the PPA is always current, so for now we
probably don't need to bother with building tags. Moreover, if we were only
building tags, then the PPA would get out of date between tagged releases.
That's the motivation for having both packages available, but since fluxgui
seems pretty stable, it's probably not worth bothering with the two
concurrent releases.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/xflux-gui/xflux-gui/issues/53#issuecomment-282452087>,
or mute the thread
