### ISSUE TITLE
Screen does not dim on Elementary Loki

### ISSUE THREAD

**Issue by arjunmenon** [xflux-gui/xflux-gui#77]
Hey
On Elementary Loki 0.4.1, the screen does not dim. Nothing happens when you do preview as well.
Is it not supported on 16.04 ubuntu distros?

It used to work on the previous version of Elementary, 0.3.2 - 14.04 based distro

--
Installed via `deb` package

**Comment by ntc2** [comment]
Please verify that you aren't experienceing Issue #27 by running `xflux` manually as described there.

**Comment by arjunmenon** [comment]
Looks like it.
Maybe you guys can add support for Redshift as well. Would be shame if going forward this project becomes abandoned, simply because xflux was abandoned. 
Closing for now. 
Yours is a very robust software. Please don't stop.

**Comment by ntc2** [comment]
Adding support for Redshift is an interesting idea. It does seem that `xflux` is basically unmaintained at this point, and since it's closed source there's not much we can do to help (not that I personally would know how to fix `xflux`, but probably someone would). Redshift on the other hand is open source, and currently maintained (version 1.11 was released in 2016).

However, there is already a Redshift GUI of sorts, [`redshift-gtk`](https://github.com/jonls/redshift), so it's not clear if it would make more sense to support Redshift in `fluxgui`, or simply add features to `redshift-gtk` (assuming the maintainer would be open to that). Right now, the Redshift GTK is very simple, providing a way to do things like pause or quit the app, but not configure it. The configuration is provided via a text file, or on the command line. But in my experience, this is not a problem.

I use `redshift-gtk` on my work computer where Issue #27 stops me from using `fluxgui`, and I find it quite easy to use (in fact, it's better than `fluxgui` in that it lets you set a daytime temperature as well). Here's my config file:
```
 cat ~/.config/redshift.conf 
; See https://wiki.archlinux.org/index.php/redshift#Configuration.
;
; To make redshift autostart on boot, run `redshift-gtk` manually
; once, click on the icon, and choose "autostart". The autostart file
; appears in `~/.config/autostart/redshift-gtk.desktop`.

; Global settings for redshift
[redshift]
; Set the day and night screen temperatures (Neutral is 6500K)
temp-day=4200
temp-night=2500

; Provide the lat/lon myself.
location-provider=manual

; The location provider config.
[manual]
; Portland.
lat=45.52
lon=-122.68
```
Pretty simple!

If the `redshift-gtk` maintainer was open to a pull request adding support for setting the location, daytime temp, and nighttime temp in the GUI, then I don't think there would be any reason to maintain `fluxgui` anymore.
